import {
  PrismaClient,
  Gender,
  Season,
  ProductStatus,
  DiscountType,
  BannerPosition,
  Prisma,
} from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Starting development database seed...");

  // 1. Clean existing records in reverse dependency order
  await prisma.inventoryTransaction.deleteMany();
  await prisma.inventory.deleteMany();
  await prisma.cartItem.deleteMany();
  await prisma.cart.deleteMany();
  await prisma.wishlistItem.deleteMany();
  await prisma.wishlist.deleteMany();
  await prisma.orderItem.deleteMany();
  await prisma.payment.deleteMany();
  await prisma.order.deleteMany();
  await prisma.review.deleteMany();
  await prisma.schoolUniform.deleteMany();
  await prisma.productImage.deleteMany();
  await prisma.productVariant.deleteMany();
  await prisma.product.deleteMany();
  await prisma.category.deleteMany();
  await prisma.school.deleteMany();
  await prisma.brand.deleteMany();
  await prisma.coupon.deleteMany();
  await prisma.banner.deleteMany();

  console.log("🧹 Cleaned existing database tables");

  // 2. Seed Brands
  const brandsData = [
    { name: "TirupatiBalajee", slug: "tirupati-balajee", description: "In-house premium school uniform & essentials manufacturer.", displayOrder: 1 },
    { name: "Van Heusen Kids", slug: "van-heusen-kids", description: "Premium formal school apparel and blazers.", displayOrder: 2 },
    { name: "Allen Solly Junior", slug: "allen-solly-junior", description: "Contemporary school wear and casuals.", displayOrder: 3 },
    { name: "Bata", slug: "bata", description: "Durable school leather shoes, canvas shoes, and sportswear.", displayOrder: 4 },
    { name: "Nivia", slug: "nivia", description: "Sports kits, track pants, and athletic accessories.", displayOrder: 5 },
    { name: "Cello", slug: "cello", description: "BPA-free insulated water bottles and steel lunch boxes.", displayOrder: 6 },
    { name: "Camlin", slug: "camlin", description: "Quality geometry boxes, art kits, and school stationery.", displayOrder: 7 },
  ];

  const brandMap = new Map<string, string>();
  for (const b of brandsData) {
    const brand = await prisma.brand.create({ data: b });
    brandMap.set(b.slug, brand.id);
  }
  console.log(`✅ Seeded ${brandMap.size} Brands`);

  // 3. Seed Schools
  const schoolsData = [
    {
      name: "Delhi Public School (DPS)",
      slug: "delhi-public-school",
      board: "CBSE",
      city: "New Delhi",
      state: "Delhi NCR",
      description: "Official prescribed uniforms and accessories for Delhi Public School branches across India.",
    },
    {
      name: "Kendriya Vidyalaya (KV)",
      slug: "kendriya-vidyalaya",
      board: "CBSE",
      city: "National",
      state: "All India",
      description: "Standardized KV uniforms for boys and girls according to KVS guidelines.",
    },
    {
      name: "Ryan International School",
      slug: "ryan-international",
      board: "ICSE / CBSE",
      city: "Mumbai",
      state: "Maharashtra",
      description: "Prescribed summer and winter uniform sets for Ryan International Group of Schools.",
    },
    {
      name: "DAV Public School",
      slug: "dav-public-school",
      board: "CBSE",
      city: "National",
      state: "All India",
      description: "Official DAV uniform sets, lab coats, and house accessories.",
    },
    {
      name: "Army Public School (APS)",
      slug: "army-public-school",
      board: "CBSE",
      city: "New Delhi",
      state: "Delhi NCR",
      description: "Durable drill and class uniforms for Army Public School students.",
    },
    {
      name: "St. Xavier's High School",
      slug: "st-xaviers-school",
      board: "ICSE",
      city: "Kolkata",
      state: "West Bengal",
      description: "Formal checked and plain uniform sets for St. Xavier's branches.",
    },
  ];

  const schoolMap = new Map<string, string>();
  for (const s of schoolsData) {
    const school = await prisma.school.create({ data: s });
    schoolMap.set(s.slug, school.id);
  }
  console.log(`✅ Seeded ${schoolMap.size} Schools`);

  // 4. Seed Hierarchical Categories (10 Main + Subcategories)
  const categoriesStructure = [
    {
      name: "School Uniforms",
      slug: "school-uniforms",
      description: "Official and general school uniforms for all seasons and grades.",
      displayOrder: 1,
      children: [
        { name: "Summer Dress", slug: "summer-dress", description: "Breathable cotton blend summer uniforms." },
        { name: "Winter Dress", slug: "winter-dress", description: "Blazers, sweaters, cardigans, and warmers." },
        { name: "Boys Uniforms", slug: "boys-uniforms", description: "Shirts, shorts, trousers, and ties." },
        { name: "Girls Uniforms", slug: "girls-uniforms", description: "Pinafores, skirts, blouses, and dupattas." },
      ],
    },
    {
      name: "Thermals",
      slug: "thermals",
      description: "Super-soft multi-stretch thermal innerwear sets for children.",
      displayOrder: 2,
      children: [
        { name: "Boys Thermals", slug: "boys-thermals", description: "Thermal tops and bottoms for boys." },
        { name: "Girls Thermals", slug: "girls-thermals", description: "Thermal tops and bottoms for girls." },
        { name: "Thermal Sets", slug: "thermal-sets", description: "Full body winter thermal inner sets." },
      ],
    },
    {
      name: "School Shoes",
      slug: "school-shoes",
      description: "Formal black leather, white PT canvas, and sports shoes.",
      displayOrder: 3,
      children: [
        { name: "Black Oxford Shoes", slug: "black-oxford-shoes", description: "Formal school leather shoes." },
        { name: "White PT Shoes", slug: "white-pt-shoes", description: "Canvas and sports shoes for PT days." },
        { name: "Velcro School Shoes", slug: "velcro-school-shoes", description: "Easy slip-on velcro shoes for young kids." },
      ],
    },
    {
      name: "School Bags",
      slug: "school-bags",
      description: "Ergonomic, lightweight backpacks with padded shoulder straps.",
      displayOrder: 4,
      children: [
        { name: "Primary School Backpacks", slug: "primary-school-backpacks", description: "Compact bags for Nursery to Class 5." },
        { name: "Senior School Backpacks", slug: "senior-school-backpacks", description: "Multi-compartment bags for Class 6 to 12." },
      ],
    },
    {
      name: "Socks & Stockings",
      slug: "socks-stockings",
      description: "Cushioned cotton socks, knee-length socks, and warm stockings.",
      displayOrder: 5,
      children: [],
    },
    {
      name: "Belts & Accessories",
      slug: "belts-accessories",
      description: "School belts, ties, metal buckles, house badges, and hairbands.",
      displayOrder: 6,
      children: [],
    },
    {
      name: "Stationery",
      slug: "stationery",
      description: "Geometry boxes, notebooks, pens, pencils, art supplies, and book covers.",
      displayOrder: 7,
      children: [],
    },
    {
      name: "Water Bottles",
      slug: "water-bottles",
      description: "Stainless steel insulated and BPA-free school bottles.",
      displayOrder: 8,
      children: [],
    },
    {
      name: "Lunch Boxes",
      slug: "lunch-boxes",
      description: "Leak-proof stainless steel and microwave-safe tiffins.",
      displayOrder: 9,
      children: [],
    },
    {
      name: "School Accessories",
      slug: "school-accessories",
      description: "ID card holders, lab aprons, raincoats, and swimming kits.",
      displayOrder: 10,
      children: [],
    },
  ];

  const categoryMap = new Map<string, string>();
  for (const cat of categoriesStructure) {
    const parent = await prisma.category.create({
      data: {
        name: cat.name,
        slug: cat.slug,
        description: cat.description,
        displayOrder: cat.displayOrder,
      },
    });
    categoryMap.set(cat.slug, parent.id);

    if (cat.children && cat.children.length > 0) {
      for (let i = 0; i < cat.children.length; i++) {
        const child = cat.children[i];
        const childRecord = await prisma.category.create({
          data: {
            name: child.name,
            slug: child.slug,
            description: child.description,
            parentId: parent.id,
            displayOrder: i + 1,
          },
        });
        categoryMap.set(child.slug, childRecord.id);
      }
    }
  }
  console.log(`✅ Seeded ${categoryMap.size} Categories and Subcategories`);

  // 5. Seed 42 Products across all categories with 150+ Variants and Inventory
  const productsToSeed = [
    // 1. Summer Dress - Boys
    {
      name: "Boys Half Sleeve School Shirt (Classic Sky Blue)",
      slug: "boys-half-sleeve-school-shirt",
      sku: "UNIF-SHT-BS01",
      description: "Crisp cotton-poly blend half sleeve shirt designed for all-day classroom comfort and durability. Features reinforced collars and tear-resistant stitching.",
      fabricDetails: "65% Cotton, 35% Polyester. Easy iron & sweat absorbent.",
      careInstructions: "Machine wash cold. Warm iron. Do not bleach.",
      mrp: 699,
      sellingPrice: 499,
      categorySlug: "school-uniforms",
      subcategorySlug: "summer-dress",
      brandSlug: "tirupati-balajee",
      gender: Gender.BOYS,
      season: Season.SUMMER,
      isBestseller: true,
      isFeatured: true,
      rating: 4.85,
      reviewCount: 356,
      sizes: ["4Y", "6Y", "8Y", "10Y", "12Y", "14Y", "16Y"],
      colors: ["Sky Blue", "White"],
      schoolAffiliations: [
        { schoolSlug: "delhi-public-school", classGrade: "Class 1-8", uniformType: "Regular" },
        { schoolSlug: "kendriya-vidyalaya", classGrade: "Class 1-5", uniformType: "Regular" },
        { schoolSlug: "dav-public-school", classGrade: "Class 1-8", uniformType: "Regular" },
      ],
    },
    {
      name: "Boys Regular Fit School Shorts (Navy Blue)",
      slug: "boys-regular-fit-school-shorts",
      sku: "UNIF-SHT-BS02",
      description: "Durable school shorts with elasticated waistband back and side pockets for primary school boys.",
      fabricDetails: "70% Cotton Drill, 30% Poly viscose.",
      careInstructions: "Machine wash warm.",
      mrp: 599,
      sellingPrice: 399,
      categorySlug: "school-uniforms",
      subcategorySlug: "summer-dress",
      brandSlug: "tirupati-balajee",
      gender: Gender.BOYS,
      season: Season.SUMMER,
      isBestseller: true,
      isFeatured: false,
      rating: 4.70,
      reviewCount: 182,
      sizes: ["4Y", "6Y", "8Y", "10Y", "12Y"],
      colors: ["Navy Blue", "Dark Grey"],
      schoolAffiliations: [
        { schoolSlug: "delhi-public-school", classGrade: "Class 1-5", uniformType: "Regular" },
        { schoolSlug: "ryan-international", classGrade: "Class 1-5", uniformType: "Regular" },
      ],
    },
    {
      name: "Boys Pleated School Trousers (Navy Blue)",
      slug: "boys-pleated-school-trousers",
      sku: "UNIF-TRS-BS03",
      description: "Smart formal school trousers with reinforced belt loops, zip fly, and deep side pockets for senior boys.",
      fabricDetails: "Matty finish poly-viscose wrinkle-free fabric.",
      careInstructions: "Machine wash or dry clean.",
      mrp: 899,
      sellingPrice: 699,
      categorySlug: "school-uniforms",
      subcategorySlug: "summer-dress",
      brandSlug: "allen-solly-junior",
      gender: Gender.BOYS,
      season: Season.ALL_SEASON,
      isBestseller: true,
      isFeatured: true,
      rating: 4.80,
      reviewCount: 245,
      sizes: ["28", "30", "32", "34", "36", "38"],
      colors: ["Navy Blue", "Charcoal Grey"],
      schoolAffiliations: [
        { schoolSlug: "delhi-public-school", classGrade: "Class 6-12", uniformType: "Regular" },
        { schoolSlug: "dav-public-school", classGrade: "Class 6-12", uniformType: "Regular" },
        { schoolSlug: "army-public-school", classGrade: "Class 6-12", uniformType: "Regular" },
      ],
    },
    // 2. Summer Dress - Girls
    {
      name: "Girls School Pinafore Dress (Navy Blue)",
      slug: "girls-school-pinafore-dress",
      sku: "UNIF-PIN-GL01",
      description: "Classic V-neck box-pleat pinafore with side buckle adjustment and concealed zipper pocket.",
      fabricDetails: "Heavyweight durable cotton-viscose blend.",
      careInstructions: "Machine wash gentle cycle.",
      mrp: 1099,
      sellingPrice: 799,
      categorySlug: "school-uniforms",
      subcategorySlug: "summer-dress",
      brandSlug: "tirupati-balajee",
      gender: Gender.GIRLS,
      season: Season.ALL_SEASON,
      isBestseller: true,
      isFeatured: true,
      rating: 4.90,
      reviewCount: 412,
      sizes: ["4Y", "6Y", "8Y", "10Y", "12Y", "14Y"],
      colors: ["Navy Blue", "Bottle Green"],
      schoolAffiliations: [
        { schoolSlug: "dav-public-school", classGrade: "Class 1-8", uniformType: "Regular" },
        { schoolSlug: "st-xaviers-school", classGrade: "Class 1-8", uniformType: "Regular" },
      ],
    },
    {
      name: "Girls Pleated School Skirt (Knife Pleat)",
      slug: "girls-pleated-school-skirt",
      sku: "UNIF-SKT-GL02",
      description: "Neat knife-pleated school skirt with elastic waist extender for comfortable everyday movement.",
      fabricDetails: "Poly-viscose wrinkle-resistant.",
      careInstructions: "Machine wash cold.",
      mrp: 699,
      sellingPrice: 499,
      categorySlug: "school-uniforms",
      subcategorySlug: "summer-dress",
      brandSlug: "tirupati-balajee",
      gender: Gender.GIRLS,
      season: Season.SUMMER,
      isBestseller: true,
      isFeatured: false,
      rating: 4.75,
      reviewCount: 198,
      sizes: ["6Y", "8Y", "10Y", "12Y", "14Y", "16Y"],
      colors: ["Navy Blue", "Dark Grey", "Maroon"],
      schoolAffiliations: [
        { schoolSlug: "delhi-public-school", classGrade: "Class 6-12", uniformType: "Regular" },
        { schoolSlug: "kendriya-vidyalaya", classGrade: "Class 6-10", uniformType: "Regular" },
      ],
    },
    {
      name: "Girls Half Sleeve Uniform Blouse (White / Sky Blue)",
      slug: "girls-half-sleeve-uniform-blouse",
      sku: "UNIF-BLS-GL03",
      description: "Tailored school blouse with Peter Pan collar and breathable sweat-resistant cotton weave.",
      fabricDetails: "70% Cotton, 30% Polyester.",
      careInstructions: "Machine wash cold.",
      mrp: 649,
      sellingPrice: 449,
      categorySlug: "school-uniforms",
      subcategorySlug: "summer-dress",
      brandSlug: "tirupati-balajee",
      gender: Gender.GIRLS,
      season: Season.SUMMER,
      isBestseller: false,
      isFeatured: false,
      rating: 4.65,
      reviewCount: 110,
      sizes: ["4Y", "6Y", "8Y", "10Y", "12Y", "14Y"],
      colors: ["White", "Sky Blue"],
      schoolAffiliations: [
        { schoolSlug: "ryan-international", classGrade: "Class 1-8", uniformType: "Regular" },
      ],
    },
    // 3. Winter Dress - Blazers, Sweaters & Cardigans
    {
      name: "Premium School Uniform Blazer (Single Breasted)",
      slug: "premium-school-uniform-blazer",
      sku: "UNIF-BLZ-WN01",
      description: "Fully lined wool-blend tailored school blazer with metallic school crest buttons and chest patch pocket.",
      fabricDetails: "60% Wool, 40% Polyester with satin lining.",
      careInstructions: "Dry clean only.",
      mrp: 2499,
      sellingPrice: 1799,
      categorySlug: "school-uniforms",
      subcategorySlug: "winter-dress",
      brandSlug: "van-heusen-kids",
      gender: Gender.UNISEX,
      season: Season.WINTER,
      isBestseller: true,
      isFeatured: true,
      rating: 4.95,
      reviewCount: 380,
      sizes: ["26", "28", "30", "32", "34", "36", "38", "40"],
      colors: ["Navy Blue", "Bottle Green", "Maroon"],
      schoolAffiliations: [
        { schoolSlug: "delhi-public-school", classGrade: "Class 6-12", uniformType: "Winter Blazer" },
        { schoolSlug: "ryan-international", classGrade: "Class 6-12", uniformType: "Winter Blazer" },
        { schoolSlug: "dav-public-school", classGrade: "Class 6-12", uniformType: "Winter Blazer" },
      ],
    },
    {
      name: "V-Neck Sleeveless School Sweater (Pure Acrylic Wool)",
      slug: "v-neck-sleeveless-school-sweater",
      sku: "UNIF-SWT-WN02",
      description: "Soft non-itchy ribbed V-neck slipover sweater with dual contrast neck stripes.",
      fabricDetails: "100% Cashmilon soft acrylic yarn.",
      careInstructions: "Hand wash or gentle wool cycle.",
      mrp: 899,
      sellingPrice: 599,
      categorySlug: "school-uniforms",
      subcategorySlug: "winter-dress",
      brandSlug: "tirupati-balajee",
      gender: Gender.UNISEX,
      season: Season.WINTER,
      isBestseller: true,
      isFeatured: false,
      rating: 4.80,
      reviewCount: 290,
      sizes: ["24", "26", "28", "30", "32", "34", "36", "38"],
      colors: ["Navy Blue", "Grey", "Maroon"],
      schoolAffiliations: [
        { schoolSlug: "delhi-public-school", classGrade: "Class 1-12", uniformType: "Regular" },
        { schoolSlug: "kendriya-vidyalaya", classGrade: "Class 1-12", uniformType: "Regular" },
      ],
    },
    {
      name: "Full Sleeve School Cardigan with Button Front",
      slug: "full-sleeve-school-cardigan",
      sku: "UNIF-CRD-WN03",
      description: "Cozy button-down full sleeve cardigan with reinforced elbows and dual pockets for girls.",
      fabricDetails: "High-bulk acrylic wool blend.",
      careInstructions: "Machine wash cold gentle.",
      mrp: 1199,
      sellingPrice: 799,
      categorySlug: "school-uniforms",
      subcategorySlug: "winter-dress",
      brandSlug: "tirupati-balajee",
      gender: Gender.GIRLS,
      season: Season.WINTER,
      isBestseller: false,
      isFeatured: false,
      rating: 4.70,
      reviewCount: 145,
      sizes: ["26", "28", "30", "32", "34", "36"],
      colors: ["Navy Blue", "Bottle Green"],
      schoolAffiliations: [
        { schoolSlug: "st-xaviers-school", classGrade: "Class 1-8", uniformType: "Regular" },
      ],
    },
    // 4. Thermals
    {
      name: "Kids Ultra-Warm Thermal Inner Set (Top + Bottom)",
      slug: "kids-thermal-set-top-bottom",
      sku: "THRM-SET-01",
      description: "3-layer thermal active fleece set with micro-brushed inner lining for extreme morning winter warmth.",
      fabricDetails: "Poly-cotton fleece with antibacterial anti-static coating.",
      careInstructions: "Machine wash cold.",
      mrp: 899,
      sellingPrice: 599,
      categorySlug: "thermals",
      subcategorySlug: "thermal-sets",
      brandSlug: "tirupati-balajee",
      gender: Gender.UNISEX,
      season: Season.WINTER,
      isBestseller: true,
      isFeatured: true,
      rating: 4.90,
      reviewCount: 520,
      sizes: ["4Y", "6Y", "8Y", "10Y", "12Y", "14Y", "16Y"],
      colors: ["Charcoal Grey", "Off White", "Black"],
      schoolAffiliations: [],
    },
    {
      name: "Boys Thermal Long Sleeve Top (Body Fit)",
      slug: "boys-thermal-top-charcoal",
      sku: "THRM-TOP-B02",
      description: "Slim-fit thermal inner shirt that stays completely invisible under white school shirts.",
      fabricDetails: "95% Cotton, 5% Spandex brushed rib.",
      careInstructions: "Machine wash.",
      mrp: 499,
      sellingPrice: 349,
      categorySlug: "thermals",
      subcategorySlug: "boys-thermals",
      brandSlug: "tirupati-balajee",
      gender: Gender.BOYS,
      season: Season.WINTER,
      isBestseller: false,
      isFeatured: false,
      rating: 4.65,
      reviewCount: 88,
      sizes: ["6Y", "8Y", "10Y", "12Y", "14Y"],
      colors: ["Off White", "Grey"],
      schoolAffiliations: [],
    },
    {
      name: "Girls Thermal Fleece Leggings (Body Warmer)",
      slug: "girls-thermal-fleece-leggings",
      sku: "THRM-BOT-G03",
      description: "Thermal inner tights designed to wear under school skirts and pinafores during winter.",
      fabricDetails: "Microfiber thermal fleece.",
      careInstructions: "Machine wash warm.",
      mrp: 499,
      sellingPrice: 349,
      categorySlug: "thermals",
      subcategorySlug: "girls-thermals",
      brandSlug: "tirupati-balajee",
      gender: Gender.GIRLS,
      season: Season.WINTER,
      isBestseller: false,
      isFeatured: false,
      rating: 4.75,
      reviewCount: 130,
      sizes: ["4Y", "6Y", "8Y", "10Y", "12Y"],
      colors: ["Black", "Skin / Nude", "Off White"],
      schoolAffiliations: [],
    },
    // 5. School Shoes
    {
      name: "Classic School Oxford Leather Shoes (Unisex)",
      slug: "classic-school-oxford-shoes",
      sku: "SHOE-OXF-01",
      description: "High-shine genuine synthetic leather school shoes with anti-skid TPR soles and cushioned memory foam footbed.",
      fabricDetails: "Premium faux leather upper, flexible rubber sole.",
      careInstructions: "Wipe with damp cloth and apply black polish.",
      mrp: 1399,
      sellingPrice: 999,
      categorySlug: "school-shoes",
      subcategorySlug: "black-oxford-shoes",
      brandSlug: "bata",
      gender: Gender.UNISEX,
      season: Season.ALL_SEASON,
      isBestseller: true,
      isFeatured: true,
      rating: 4.88,
      reviewCount: 640,
      sizes: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
      colors: ["Black"],
      schoolAffiliations: [],
    },
    {
      name: "White PT Sports Canvas Shoes (Lace Up)",
      slug: "white-pt-sports-canvas-shoes",
      sku: "SHOE-PTS-02",
      description: "Breathable canvas PT shoes with non-marking rubber soles required for school drill and games periods.",
      fabricDetails: "100% Breathable cotton canvas with vulcanized sole.",
      careInstructions: "Hand wash with mild detergent.",
      mrp: 699,
      sellingPrice: 449,
      categorySlug: "school-shoes",
      subcategorySlug: "white-pt-shoes",
      brandSlug: "bata",
      gender: Gender.UNISEX,
      season: Season.ALL_SEASON,
      isBestseller: true,
      isFeatured: false,
      rating: 4.70,
      reviewCount: 310,
      sizes: ["11C", "12C", "13C", "1", "2", "3", "4", "5", "6", "7", "8"],
      colors: ["White"],
      schoolAffiliations: [],
    },
    {
      name: "Kids Easy-Straps School Shoes (Double Velcro)",
      slug: "kids-easy-straps-velcro-shoes",
      sku: "SHOE-VLC-03",
      description: "Dual hook-and-loop velcro fastener shoes specially crafted for nursery and primary school students.",
      fabricDetails: "Scuff-resistant synthetic leather.",
      careInstructions: "Wipe clean.",
      mrp: 999,
      sellingPrice: 699,
      categorySlug: "school-shoes",
      subcategorySlug: "velcro-school-shoes",
      brandSlug: "bata",
      gender: Gender.UNISEX,
      season: Season.ALL_SEASON,
      isBestseller: true,
      isFeatured: false,
      rating: 4.90,
      reviewCount: 275,
      sizes: ["8C", "9C", "10C", "11C", "12C", "13C", "1", "2"],
      colors: ["Black"],
      schoolAffiliations: [],
    },
    // 6. School Bags
    {
      name: "Ergonomic Multi-Compartment School Backpack (32L)",
      slug: "ergonomic-multi-compartment-school-backpack",
      sku: "BAG-ERG-01",
      description: "Heavy-duty 32L water-repellent school bag with spinal support padding, laptop sleeve, and dual water bottle holders.",
      fabricDetails: "900D High-density waterproof Polyester.",
      careInstructions: "Hand wash cold.",
      mrp: 1499,
      sellingPrice: 899,
      categorySlug: "school-bags",
      subcategorySlug: "senior-school-backpacks",
      brandSlug: "tirupati-balajee",
      gender: Gender.UNISEX,
      season: Season.ALL_SEASON,
      isBestseller: true,
      isFeatured: true,
      rating: 4.85,
      reviewCount: 220,
      sizes: ["Standard 32L"],
      colors: ["Navy Blue", "Teal Blue", "Black & Red"],
      schoolAffiliations: [],
    },
    {
      name: "Kids Cartoon Lightweight School Bag (Primary)",
      slug: "kids-cartoon-lightweight-school-bag",
      sku: "BAG-KID-02",
      description: "Ultra-lightweight 18L bag with soft shoulder cushioning and reflective safety strips for small kids.",
      fabricDetails: "Water-resistant 600D fabric.",
      careInstructions: "Wipe clean with cloth.",
      mrp: 999,
      sellingPrice: 599,
      categorySlug: "school-bags",
      subcategorySlug: "primary-school-backpacks",
      brandSlug: "tirupati-balajee",
      gender: Gender.UNISEX,
      season: Season.ALL_SEASON,
      isBestseller: false,
      isFeatured: false,
      rating: 4.70,
      reviewCount: 140,
      sizes: ["Compact 18L"],
      colors: ["Blue Space", "Pink Butterfly", "Yellow Dino"],
      schoolAffiliations: [],
    },
    // 7. Socks & Stockings
    {
      name: "Cushioned Cotton School Socks (Pack of 3)",
      slug: "cushioned-cotton-school-socks-pack-of-3",
      sku: "SCK-CSH-01",
      description: "Premium combed cotton crew socks with reinforced heels and seamless toe closure for blister-free school days.",
      fabricDetails: "85% Combed Cotton, 12% Spandex, 3% Elastic.",
      careInstructions: "Machine wash warm.",
      mrp: 399,
      sellingPrice: 249,
      categorySlug: "socks-stockings",
      brandSlug: "tirupati-balajee",
      gender: Gender.UNISEX,
      season: Season.ALL_SEASON,
      isBestseller: true,
      isFeatured: false,
      rating: 4.80,
      reviewCount: 480,
      sizes: ["Small (4-7Y)", "Medium (8-12Y)", "Large (13Y+)"],
      colors: ["White with Navy Bands", "Plain White", "Plain Navy"],
      schoolAffiliations: [],
    },
    {
      name: "Girls Winter Woolen Knee-High Stockings",
      slug: "girls-winter-woolen-knee-high-stockings",
      sku: "SCK-STK-02",
      description: "Thick stretch-fit knee stockings keeping schoolgirls warm during cold morning assemblies.",
      fabricDetails: "Acrylic wool blend with high elasticity.",
      careInstructions: "Hand wash cold.",
      mrp: 299,
      sellingPrice: 199,
      categorySlug: "socks-stockings",
      brandSlug: "tirupati-balajee",
      gender: Gender.GIRLS,
      season: Season.WINTER,
      isBestseller: false,
      isFeatured: false,
      rating: 4.60,
      reviewCount: 75,
      sizes: ["Small (4-8Y)", "Medium (9-14Y)"],
      colors: ["Black", "Navy Blue"],
      schoolAffiliations: [],
    },
    // 8. Belts & Accessories
    {
      name: "Universal Adjustable School Uniform Belt",
      slug: "universal-adjustable-school-uniform-belt",
      sku: "ACC-BLT-01",
      description: "Strong nylon braided web belt with metal chrome-finish sliding friction lock buckle.",
      fabricDetails: "100% High-tensile Nylon webbing with alloy buckle.",
      careInstructions: "Wipe clean.",
      mrp: 249,
      sellingPrice: 149,
      categorySlug: "belts-accessories",
      brandSlug: "tirupati-balajee",
      gender: Gender.UNISEX,
      season: Season.ALL_SEASON,
      isBestseller: true,
      isFeatured: false,
      rating: 4.75,
      reviewCount: 310,
      sizes: ["Free Size (Adjustable up to 36 inch)"],
      colors: ["Navy Blue with White Stripe", "Plain Black", "Maroon Stripe"],
      schoolAffiliations: [
        { schoolSlug: "delhi-public-school", classGrade: "Class 1-12", uniformType: "Regular" },
        { schoolSlug: "kendriya-vidyalaya", classGrade: "Class 1-12", uniformType: "Regular" },
      ],
    },
    {
      name: "School Uniform Tie (Woven Microfiber)",
      slug: "school-uniform-tie-woven-microfiber",
      sku: "ACC-TIE-02",
      description: "Stain-resistant pre-tied or self-tie uniform necktie with fine twill woven stripes.",
      fabricDetails: "100% Jacquard Microfiber Silk-Touch.",
      careInstructions: "Spot clean only.",
      mrp: 249,
      sellingPrice: 149,
      categorySlug: "belts-accessories",
      brandSlug: "tirupati-balajee",
      gender: Gender.UNISEX,
      season: Season.ALL_SEASON,
      isBestseller: true,
      isFeatured: false,
      rating: 4.80,
      reviewCount: 220,
      sizes: ["Junior (12 inch)", "Senior (16 inch)"],
      colors: ["Navy / Gold Diagonal Stripe", "Maroon / Silver Stripe"],
      schoolAffiliations: [
        { schoolSlug: "delhi-public-school", classGrade: "Class 1-12", uniformType: "Regular" },
        { schoolSlug: "st-xaviers-school", classGrade: "Class 1-12", uniformType: "Regular" },
      ],
    },
    {
      name: "Metal Enamelled House Captain Badges",
      slug: "metal-enamelled-house-captain-badges",
      sku: "ACC-BDG-03",
      description: "High-gloss gold plated enamel badges with safety brooch pin for school prefects and house captains.",
      fabricDetails: "Zinc alloy with hard enamel glaze.",
      careInstructions: "Keep dry.",
      mrp: 149,
      sellingPrice: 99,
      categorySlug: "belts-accessories",
      brandSlug: "tirupati-balajee",
      gender: Gender.UNISEX,
      season: Season.ALL_SEASON,
      isBestseller: false,
      isFeatured: false,
      rating: 4.90,
      reviewCount: 160,
      sizes: ["Standard 45mm"],
      colors: ["Red House", "Blue House", "Green House", "Yellow House"],
      schoolAffiliations: [],
    },
    // 9. Stationery
    {
      name: "Camlin Exam Master Geometry Mathematical Box",
      slug: "camlin-exam-master-geometry-box",
      sku: "STAT-GEO-01",
      description: "Rust-free self-centering compass and divider with transparent precision markings for geometry classes.",
      fabricDetails: "High-grade alloy tools in metallic tin box.",
      careInstructions: "Keep tools in designated slots.",
      mrp: 180,
      sellingPrice: 140,
      categorySlug: "stationery",
      brandSlug: "camlin",
      gender: Gender.UNISEX,
      season: Season.ALL_SEASON,
      isBestseller: true,
      isFeatured: false,
      rating: 4.85,
      reviewCount: 490,
      sizes: ["10 Pieces Kit"],
      colors: ["Standard Metal Tin"],
      schoolAffiliations: [],
    },
    {
      name: "School Notebooks Bundle (Pack of 6 Long Registers)",
      slug: "school-notebooks-bundle-pack-of-6",
      sku: "STAT-NTB-02",
      description: "70 GSM high-brightness paper with waterproof laminated covers, single line ruling with index pages.",
      fabricDetails: "Eco-friendly elemental chlorine-free paper.",
      careInstructions: "Store in dry place.",
      mrp: 420,
      sellingPrice: 320,
      categorySlug: "stationery",
      brandSlug: "camlin",
      gender: Gender.UNISEX,
      season: Season.ALL_SEASON,
      isBestseller: true,
      isFeatured: false,
      rating: 4.75,
      reviewCount: 310,
      sizes: ["172 Pages x 6 Books"],
      colors: ["Multicolor Covers"],
      schoolAffiliations: [],
    },
    // 10. Water Bottles
    {
      name: "Cello Puro Insulated Stainless Steel School Bottle (750ml)",
      slug: "cello-puro-insulated-steel-bottle-750ml",
      sku: "BOT-STE-01",
      description: "Double-wall vacuum insulated flask keeping water chilled for up to 18 hours in hot summer school days.",
      fabricDetails: "304 Food-grade Rustproof Stainless Steel.",
      careInstructions: "Hand wash with soft sponge.",
      mrp: 799,
      sellingPrice: 549,
      categorySlug: "water-bottles",
      brandSlug: "cello",
      gender: Gender.UNISEX,
      season: Season.ALL_SEASON,
      isBestseller: true,
      isFeatured: true,
      rating: 4.90,
      reviewCount: 380,
      sizes: ["750ml", "1000ml"],
      colors: ["Royal Blue", "Pastel Pink", "Matte Black", "Cyan"],
      schoolAffiliations: [],
    },
    // 11. Lunch Boxes
    {
      name: "Cello Maxima Stainless Steel 3-Tier Lunch Box with Thermal Bag",
      slug: "cello-maxima-3tier-steel-lunch-box",
      sku: "LNC-BX-01",
      description: "100% leak-proof airtight clip lock containers with insulated fabric carry pouch and steel spoon.",
      fabricDetails: "Food grade SS 304 containers with BPA-free silicone seals.",
      careInstructions: "Dishwasher safe containers.",
      mrp: 899,
      sellingPrice: 649,
      categorySlug: "lunch-boxes",
      brandSlug: "cello",
      gender: Gender.UNISEX,
      season: Season.ALL_SEASON,
      isBestseller: true,
      isFeatured: false,
      rating: 4.80,
      reviewCount: 290,
      sizes: ["3 Containers (850ml)"],
      colors: ["Blue Pouch", "Grey Pouch", "Pink Pouch"],
      schoolAffiliations: [],
    },
    // 12. PT & Sports Uniforms
    {
      name: "School PT Track Pants with Dual Side Stripes",
      slug: "school-pt-track-pants-stripes",
      sku: "SPT-TRK-01",
      description: "Breathable polyester track pants with elastic drawcord waist and zipper pockets for physical education days.",
      fabricDetails: "Quick-dry micro-poly interlock knit.",
      careInstructions: "Machine wash cold.",
      mrp: 699,
      sellingPrice: 479,
      categorySlug: "school-uniforms",
      brandSlug: "nivia",
      gender: Gender.UNISEX,
      season: Season.ALL_SEASON,
      isBestseller: true,
      isFeatured: false,
      rating: 4.70,
      reviewCount: 165,
      sizes: ["4Y", "6Y", "8Y", "10Y", "12Y", "14Y", "16Y"],
      colors: ["Navy with White Stripes", "White with Navy Stripes", "Black with Red"],
      schoolAffiliations: [
        { schoolSlug: "delhi-public-school", classGrade: "Class 1-12", uniformType: "Sports/PT" },
        { schoolSlug: "ryan-international", classGrade: "Class 1-12", uniformType: "Sports/PT" },
      ],
    },
    {
      name: "School House Polo T-Shirt (Cotton Pique)",
      slug: "school-house-polo-tshirt",
      sku: "SPT-POL-02",
      description: "Collar polo t-shirt with ribbed cuffs and contrast tipping for inter-house sports competitions.",
      fabricDetails: "100% Combed Cotton Pique 220 GSM.",
      careInstructions: "Machine wash warm.",
      mrp: 499,
      sellingPrice: 349,
      categorySlug: "school-uniforms",
      brandSlug: "tirupati-balajee",
      gender: Gender.UNISEX,
      season: Season.SUMMER,
      isBestseller: true,
      isFeatured: false,
      rating: 4.80,
      reviewCount: 215,
      sizes: ["4Y", "6Y", "8Y", "10Y", "12Y", "14Y", "16Y"],
      colors: ["Red", "Blue", "Green", "Yellow"],
      schoolAffiliations: [
        { schoolSlug: "delhi-public-school", classGrade: "Class 1-12", uniformType: "House" },
        { schoolSlug: "kendriya-vidyalaya", classGrade: "Class 1-12", uniformType: "House" },
      ],
    },
    // 13. Lab Coats & Aprons
    {
      name: "White School Science Laboratory Coat (Unisex)",
      slug: "white-school-science-lab-coat",
      sku: "ACC-LAB-01",
      description: "Full sleeve 100% cotton lab apron with front button placket and deep reagent pockets for science practicals.",
      fabricDetails: "100% Drill Cotton Heavyweight.",
      careInstructions: "Machine wash hot.",
      mrp: 599,
      sellingPrice: 399,
      categorySlug: "school-accessories",
      brandSlug: "tirupati-balajee",
      gender: Gender.UNISEX,
      season: Season.ALL_SEASON,
      isBestseller: false,
      isFeatured: false,
      rating: 4.85,
      reviewCount: 140,
      sizes: ["30 (Class 9-10)", "34 (Class 11)", "38 (Class 12)"],
      colors: ["Pure White"],
      schoolAffiliations: [
        { schoolSlug: "delhi-public-school", classGrade: "Class 9-12", uniformType: "Regular" },
        { schoolSlug: "dav-public-school", classGrade: "Class 9-12", uniformType: "Regular" },
      ],
    },
    // 14. Winter Accessories - Caps & Gloves
    {
      name: "Kids Winter Woolen Beanie Cap & Gloves Set",
      slug: "kids-winter-woolen-cap-gloves-set",
      sku: "ACC-CAP-02",
      description: "Thermal fleece-lined knitted cap and grip gloves for freezing winter morning transit.",
      fabricDetails: "Double layer acrylic knit with soft fleece.",
      careInstructions: "Hand wash cold.",
      mrp: 399,
      sellingPrice: 249,
      categorySlug: "school-accessories",
      brandSlug: "tirupati-balajee",
      gender: Gender.UNISEX,
      season: Season.WINTER,
      isBestseller: false,
      isFeatured: false,
      rating: 4.70,
      reviewCount: 95,
      sizes: ["Junior (4-8Y)", "Senior (9-14Y)"],
      colors: ["Navy Blue", "Dark Grey", "Maroon"],
      schoolAffiliations: [],
    },
    // 15. Boys Full Sleeve Winter Shirt
    {
      name: "Boys Full Sleeve Oxford Winter Shirt",
      slug: "boys-full-sleeve-oxford-winter-shirt",
      sku: "UNIF-SHT-BS04",
      description: "Heavyweight brushed cotton long sleeve uniform shirt designed for chilly classroom weather.",
      fabricDetails: "100% Thermal-finish cotton.",
      careInstructions: "Machine wash warm.",
      mrp: 799,
      sellingPrice: 599,
      categorySlug: "school-uniforms",
      subcategorySlug: "winter-dress",
      brandSlug: "tirupati-balajee",
      gender: Gender.BOYS,
      season: Season.WINTER,
      isBestseller: true,
      isFeatured: false,
      rating: 4.80,
      reviewCount: 164,
      sizes: ["6Y", "8Y", "10Y", "12Y", "14Y", "16Y"],
      colors: ["White", "Sky Blue"],
      schoolAffiliations: [
        { schoolSlug: "delhi-public-school", classGrade: "Class 1-12", uniformType: "Regular" },
      ],
    },
    // 16. Girls Full Sleeve Winter Blouse
    {
      name: "Girls Full Sleeve Tailored School Blouse",
      slug: "girls-full-sleeve-tailored-school-blouse",
      sku: "UNIF-BLS-GL04",
      description: "Full sleeve tailored uniform blouse with buttoned cuffs and reinforced stitching.",
      fabricDetails: "75% Cotton, 25% Polyester.",
      careInstructions: "Machine wash gentle.",
      mrp: 799,
      sellingPrice: 599,
      categorySlug: "school-uniforms",
      subcategorySlug: "winter-dress",
      brandSlug: "tirupati-balajee",
      gender: Gender.GIRLS,
      season: Season.WINTER,
      isBestseller: false,
      isFeatured: false,
      rating: 4.75,
      reviewCount: 112,
      sizes: ["6Y", "8Y", "10Y", "12Y", "14Y"],
      colors: ["White", "Sky Blue"],
      schoolAffiliations: [
        { schoolSlug: "dav-public-school", classGrade: "Class 1-12", uniformType: "Regular" },
      ],
    },
    // 17. School Tracksuit Jacket
    {
      name: "Sports Tracksuit Zipper Jacket with School Piping",
      slug: "sports-tracksuit-zipper-jacket",
      sku: "SPT-JCK-01",
      description: "Full-zip sports jacket with mock neck collar, side pockets, and breathable mesh lining.",
      fabricDetails: "Micro-poly interlock sports fabric.",
      careInstructions: "Machine wash cold.",
      mrp: 1199,
      sellingPrice: 849,
      categorySlug: "school-uniforms",
      brandSlug: "nivia",
      gender: Gender.UNISEX,
      season: Season.ALL_SEASON,
      isBestseller: true,
      isFeatured: false,
      rating: 4.85,
      reviewCount: 230,
      sizes: ["6Y", "8Y", "10Y", "12Y", "14Y", "S", "M", "L"],
      colors: ["Navy / White", "Green / Gold", "Royal / White"],
      schoolAffiliations: [
        { schoolSlug: "ryan-international", classGrade: "Class 1-12", uniformType: "Sports/PT" },
      ],
    },
    // 18. School Raincoat with Bag Cover Hood
    {
      name: "Waterproof School Raincoat with Backpack Expandable Pouch",
      slug: "waterproof-school-raincoat-with-backpack-pouch",
      sku: "ACC-RN-01",
      description: "Heavy-duty waterproof raincoat with reflective tape and an expandable back pocket that fits school backpacks.",
      fabricDetails: "100% Waterproof EVA / Polyester.",
      careInstructions: "Hang dry after rain.",
      mrp: 899,
      sellingPrice: 599,
      categorySlug: "school-accessories",
      brandSlug: "tirupati-balajee",
      gender: Gender.UNISEX,
      season: Season.ALL_SEASON,
      isBestseller: false,
      isFeatured: false,
      rating: 4.80,
      reviewCount: 155,
      sizes: ["Small (4-7Y)", "Medium (8-11Y)", "Large (12-16Y)"],
      colors: ["Bright Yellow", "Navy Blue", "Transparent Blue"],
      schoolAffiliations: [],
    },
    // 19. ID Card Holder & Lanyards
    {
      name: "School Student ID Card Holder & Lanyard (Pack of 2)",
      slug: "school-id-card-holder-lanyard-pack-of-2",
      sku: "ACC-LNY-01",
      description: "Heavy clear acrylic ID case with breakaway safety neck strap for students.",
      fabricDetails: "Clear hard plastic with polyester woven lanyard.",
      careInstructions: "Wipe clean.",
      mrp: 149,
      sellingPrice: 89,
      categorySlug: "school-accessories",
      brandSlug: "tirupati-balajee",
      gender: Gender.UNISEX,
      season: Season.ALL_SEASON,
      isBestseller: false,
      isFeatured: false,
      rating: 4.60,
      reviewCount: 88,
      sizes: ["Universal Standard"],
      colors: ["Navy Blue", "Royal Blue", "Red"],
      schoolAffiliations: [],
    },
    // 20. Insulated Steel Sipper Bottle
    {
      name: "Cello Sporty Insulated Straw Bottle (600ml)",
      slug: "cello-sporty-insulated-straw-bottle-600ml",
      sku: "BOT-STR-02",
      description: "Easy one-touch flip top straw lid insulated bottle for primary school kids.",
      fabricDetails: "Food-grade stainless steel with silicone straw.",
      careInstructions: "Hand wash.",
      mrp: 699,
      sellingPrice: 479,
      categorySlug: "water-bottles",
      brandSlug: "cello",
      gender: Gender.UNISEX,
      season: Season.ALL_SEASON,
      isBestseller: true,
      isFeatured: false,
      rating: 4.75,
      reviewCount: 210,
      sizes: ["600ml"],
      colors: ["Pastel Mint Green", "Sky Blue", "Coral Pink"],
      schoolAffiliations: [],
    },
    // 21. Double Decker Lunch Box
    {
      name: "Cello Duo Bento Leakproof Stainless Steel Tiffin",
      slug: "cello-duo-bento-leakproof-tiffin",
      sku: "LNC-BX-02",
      description: "2-tier stainless steel tiffin with airtight silicone sealed lids and compact handle.",
      fabricDetails: "SS 304 food contact certified.",
      careInstructions: "Dishwasher safe.",
      mrp: 699,
      sellingPrice: 499,
      categorySlug: "lunch-boxes",
      brandSlug: "cello",
      gender: Gender.UNISEX,
      season: Season.ALL_SEASON,
      isBestseller: false,
      isFeatured: false,
      rating: 4.70,
      reviewCount: 140,
      sizes: ["700ml"],
      colors: ["Aqua Blue", "Cherry Red", "Lime Green"],
      schoolAffiliations: [],
    },
    // 22. Camlin Acrylic Colours Art Set
    {
      name: "Camlin Student Acrylic Colour Set (12 Shades Tube Box)",
      slug: "camlin-student-acrylic-colour-set",
      sku: "STAT-ART-01",
      description: "Vibrant rich pigmentation non-toxic acrylic colours ideal for school art and craft projects.",
      fabricDetails: "Non-toxic certified pigments.",
      careInstructions: "Keep caps tightly closed.",
      mrp: 275,
      sellingPrice: 220,
      categorySlug: "stationery",
      brandSlug: "camlin",
      gender: Gender.UNISEX,
      season: Season.ALL_SEASON,
      isBestseller: false,
      isFeatured: false,
      rating: 4.90,
      reviewCount: 310,
      sizes: ["12 Shades Box"],
      colors: ["Standard Assorted"],
      schoolAffiliations: [],
    },
    // 23. School House Sports Cap
    {
      name: "Cotton Twill School Sports Sun Cap",
      slug: "cotton-twill-school-sports-sun-cap",
      sku: "ACC-CAP-03",
      description: "6-panel structured baseball style sun cap with embroidered eyelets and velcro size adjuster.",
      fabricDetails: "100% Heavy brushed cotton twill.",
      careInstructions: "Spot clean.",
      mrp: 199,
      sellingPrice: 129,
      categorySlug: "belts-accessories",
      brandSlug: "tirupati-balajee",
      gender: Gender.UNISEX,
      season: Season.SUMMER,
      isBestseller: false,
      isFeatured: false,
      rating: 4.65,
      reviewCount: 95,
      sizes: ["Adjustable (Junior/Senior)"],
      colors: ["Red", "Blue", "Green", "Yellow", "Navy Blue"],
      schoolAffiliations: [],
    },
    // 24. Girls Hair Ribbon & Band Set
    {
      name: "Girls School Uniform Hair Ribbons & Satin Scrunchies Set",
      slug: "girls-school-hair-ribbon-scrunchies-set",
      sku: "ACC-HR-01",
      description: "Pack of 4 satin hair ribbons, 4 elastic ponytail holders, and 2 hair clips conforming to school dress codes.",
      fabricDetails: "Satin ribbon & soft snag-free elastics.",
      careInstructions: "Hand wash.",
      mrp: 149,
      sellingPrice: 99,
      categorySlug: "belts-accessories",
      brandSlug: "tirupati-balajee",
      gender: Gender.GIRLS,
      season: Season.ALL_SEASON,
      isBestseller: false,
      isFeatured: false,
      rating: 4.80,
      reviewCount: 160,
      sizes: ["10 Pieces Pack"],
      colors: ["Navy Blue", "White", "Dark Maroon", "Bottle Green"],
      schoolAffiliations: [],
    },
    // 25. School Whistle with Lanyard
    {
      name: "Sports Coach & Drill School Whistle with Lanyard",
      slug: "sports-drill-school-whistle-lanyard",
      sku: "ACC-WHS-01",
      description: "Pealess high-decibel sports whistle with cushioned finger grip and safety neck lanyard for games captains.",
      fabricDetails: "BPA-free ABS plastic with braided lanyard.",
      careInstructions: "Rinse with warm water.",
      mrp: 129,
      sellingPrice: 79,
      categorySlug: "school-accessories",
      brandSlug: "nivia",
      gender: Gender.UNISEX,
      season: Season.ALL_SEASON,
      isBestseller: false,
      isFeatured: false,
      rating: 4.70,
      reviewCount: 65,
      sizes: ["Single Unit"],
      colors: ["Black", "Yellow", "Red"],
      schoolAffiliations: [],
    },
  ];

  let totalVariantsCreated = 0;
  let totalInventoryCreated = 0;
  let totalUniformMappings = 0;

  for (const item of productsToSeed) {
    const categoryId = categoryMap.get(item.categorySlug) || categoryMap.get("school-uniforms")!;
    const subcategoryId = item.subcategorySlug ? categoryMap.get(item.subcategorySlug) : null;
    const brandId = item.brandSlug ? brandMap.get(item.brandSlug) : null;

    const product = await prisma.product.create({
      data: {
        name: item.name,
        slug: item.slug,
        sku: item.sku,
        description: item.description,
        fabricDetails: item.fabricDetails,
        careInstructions: item.careInstructions,
        mrp: new Prisma.Decimal(item.mrp),
        sellingPrice: new Prisma.Decimal(item.sellingPrice),
        categoryId,
        subcategoryId,
        brandId,
        status: ProductStatus.PUBLISHED,
        isFeatured: item.isFeatured,
        isBestseller: item.isBestseller,
        rating: new Prisma.Decimal(item.rating),
        reviewCount: item.reviewCount,
        seoTitle: `${item.name} | TirupatiBalajee Dresses`,
        seoDescription: item.description.slice(0, 160),
      },
    });

    // Seed Primary Image
    await prisma.productImage.create({
      data: {
        productId: product.id,
        url: `/images/products/${item.slug}.png`,
        alt: item.name,
        displayOrder: 1,
        isPrimary: true,
      },
    });

    // Seed Variants for each size & color combination
    let variantIndex = 1;
    for (const size of item.sizes) {
      for (const color of item.colors) {
        const cleanSize = size.replace(/[^a-zA-Z0-9]/g, "");
        const cleanColor = color.replace(/[^a-zA-Z0-9]/g, "").toUpperCase();
        const variantSku = `${item.sku}-${cleanSize}-${cleanColor}-${variantIndex++}`;
        const variant = await prisma.productVariant.create({
          data: {
            productId: product.id,
            size,
            color,
            sku: variantSku,
            mrp: new Prisma.Decimal(item.mrp),
            sellingPrice: new Prisma.Decimal(item.sellingPrice),
            isAvailable: true,
          },
        });
        totalVariantsCreated++;

        // Seed Inventory record with realistic stock
        const stockQty = Math.floor(Math.random() * 45) + 15;
        await prisma.inventory.create({
          data: {
            variantId: variant.id,
            availableQuantity: stockQty,
            reservedQuantity: 0,
            lowStockThreshold: 5,
            warehouseLocation: "Main Delhi Warehouse - Section A",
          },
        });
        totalInventoryCreated++;
      }
    }

    // Seed School Uniform Mappings
    if (item.schoolAffiliations && item.schoolAffiliations.length > 0) {
      for (const aff of item.schoolAffiliations) {
        const schoolId = schoolMap.get(aff.schoolSlug);
        if (schoolId) {
          await prisma.schoolUniform.create({
            data: {
              schoolId,
              productId: product.id,
              season: item.season,
              gender: item.gender,
              classGrade: aff.classGrade,
              uniformType: aff.uniformType,
              isCompulsory: true,
            },
          });
          totalUniformMappings++;
        }
      }
    }
  }

  console.log(`✅ Seeded ${productsToSeed.length} Products`);
  console.log(`✅ Seeded ${totalVariantsCreated} Product Variants`);
  console.log(`✅ Seeded ${totalInventoryCreated} Inventory Records`);
  console.log(`✅ Seeded ${totalUniformMappings} School Uniform Mappings`);

  // 6. Seed Coupons
  await prisma.coupon.createMany({
    data: [
      {
        code: "SCHOOL20",
        description: "Flat 20% discount on Uniforms, Thermals & School Items",
        discountType: DiscountType.PERCENTAGE,
        discountValue: new Prisma.Decimal(20.0),
        minOrderAmount: new Prisma.Decimal(499.0),
        maxDiscountAmount: new Prisma.Decimal(500.0),
        usageLimit: 10000,
        isActive: true,
      },
      {
        code: "FREESHIP",
        description: "Free shipping on orders above ₹499",
        discountType: DiscountType.FIXED,
        discountValue: new Prisma.Decimal(70.0),
        minOrderAmount: new Prisma.Decimal(499.0),
        usageLimit: 5000,
        isActive: true,
      },
      {
        code: "WELCOME100",
        description: "₹100 Flat discount on your first school kit order",
        discountType: DiscountType.FIXED,
        discountValue: new Prisma.Decimal(100.0),
        minOrderAmount: new Prisma.Decimal(999.0),
        usageLimit: 2000,
        isActive: true,
      },
    ],
  });
  console.log("✅ Seeded Development Coupons");

  // 7. Seed Banners
  await prisma.banner.createMany({
    data: [
      {
        title: "Uniforms for Every Season",
        subtitle: "Comfort. Confidence. A Brighter Tomorrow.",
        image: "/images/hero-banner.png",
        ctaText: "SHOP SCHOOL UNIFORMS",
        ctaUrl: "/category/school-uniforms",
        badge: "School Days, Brighter Always",
        position: BannerPosition.HERO,
        displayOrder: 1,
        isActive: true,
      },
      {
        title: "Stay Cool This Summer",
        subtitle: "Comfortable Uniforms for Active Days",
        image: "/images/promo-summer.png",
        ctaText: "SHOP SUMMER DRESS",
        ctaUrl: "/category/summer-dress",
        badge: "☀️ Summer Collection",
        position: BannerPosition.PROMO_SPLIT,
        displayOrder: 1,
        isActive: true,
      },
      {
        title: "Stay Warm This Winter",
        subtitle: "Premium Winter Uniforms for Every Season",
        image: "/images/promo-winter.png",
        ctaText: "SHOP WINTER DRESS",
        ctaUrl: "/category/winter-dress",
        badge: "❄️ Winter Warmers",
        position: BannerPosition.PROMO_SPLIT,
        displayOrder: 2,
        isActive: true,
      },
      {
        title: "COMPLETE SCHOOL LOOK",
        subtitle: "Uniforms + Shoes + Accessories",
        image: "/images/promo-combo.png",
        ctaText: "SHOP COMBO SETS",
        ctaUrl: "/combos",
        badge: "Combo Pack",
        position: BannerPosition.PROMO_TRIO,
        displayOrder: 1,
        isActive: true,
      },
      {
        title: "Warmth for Every Adventure",
        subtitle: "Soft, lightweight multi-stretch thermals",
        image: "/images/promo-thermals.png",
        ctaText: "EXPLORE NOW",
        ctaUrl: "/category/thermals",
        badge: "Thermals Collection",
        position: BannerPosition.PROMO_TRIO,
        displayOrder: 2,
        isActive: true,
      },
      {
        title: "Flat 20% OFF",
        subtitle: "On Uniforms, Thermals & School Items",
        image: "/images/promo-offer.png",
        ctaText: "USE CODE: SCHOOL20",
        ctaUrl: "/offers",
        badge: "Special Offer",
        position: BannerPosition.PROMO_TRIO,
        displayOrder: 3,
        isActive: true,
      },
    ],
  });
  console.log("✅ Seeded Promotional Banners");

  console.log("🎉 Database seeding completed successfully!");
}

main()
  .catch((e) => {
    console.error("❌ Seeding failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
