export const APP_CONSTANTS = {
  DEFAULT_PAGE_SIZE: 12,
  MAX_PAGE_SIZE: 50,
  FREE_SHIPPING_THRESHOLD: 999,
  STANDARD_SHIPPING_FEE: 70,
  CURRENCY_SYMBOL: "₹",
  CURRENCY_CODE: "INR",
  SUPPORT_EMAIL: "support@tirupatibalajeedresses.com",
  SUPPORT_PHONE: "+91 98765 43210",
  STANDARD_SIZES: ["4Y", "6Y", "8Y", "10Y", "12Y", "14Y", "16Y", "S", "M", "L", "XL", "XXL"],
  FOOTWEAR_SIZES: ["9C", "10C", "11C", "12C", "13C", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
  INDIAN_STATES: [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
    "Delhi NCR",
    "Chandigarh",
  ],
  POPULAR_SCHOOLS: [
    { name: "Delhi Public School (DPS)", slug: "delhi-public-school" },
    { name: "Kendriya Vidyalaya (KV)", slug: "kendriya-vidyalaya" },
    { name: "Ryan International School", slug: "ryan-international" },
    { name: "DAV Public School", slug: "dav-public-school" },
    { name: "Army Public School (APS)", slug: "army-public-school" },
    { name: "St. Xavier's High School", slug: "st-xaviers-school" },
  ],
};
