export const siteConfig = {
  name: "TirupatiBalajee Dresses",
  shortName: "TirupatiBalajee",
  description:
    "India's premier school uniform and school essentials platform. Premium fabric, perfect fit, trusted by thousands of parents across India.",
  url: process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000",
  tagline: "School Days, Brighter Always",
  subTagline: "Uniforms for Every Season • Comfort. Confidence. A Brighter Tomorrow.",
  contact: {
    phone: "+91 98765 43210",
    email: "support@tirupatibalajeedresses.com",
    address: "124, Market Complex, Near Central School Road, New Delhi - 110001",
    hours: "Mon - Sat: 9:30 AM - 8:30 PM",
  },
  topAnnouncement: [
    { text: "🚚 Free Shipping on orders above ₹999" },
    { text: "🔄 Easy Returns & Exchanges" },
    { text: "🛡️ 100% Genuine Products" },
  ],
  quickLinks: [
    { label: "Track Order", href: "/track-order" },
    { label: "Help & Support", href: "/help" },
    { label: "Find a Store", href: "/stores" },
  ],
  navLinks: [
    { label: "SCHOOL UNIFORMS", href: "/category/school-uniforms" },
    { label: "THERMALS", href: "/category/thermals" },
    { label: "SCHOOL ITEMS", href: "/category/school-items" },
    { label: "BRANDS", href: "/brands" },
    { label: "OFFERS", href: "/offers", isSpecial: true },
  ],
  trustFeatures: [
    {
      title: "Trusted by Parents",
      description: "Over 50,000+ satisfied students & parents nationwide",
      icon: "ShieldCheck",
    },
    {
      title: "High Quality & Durable",
      description: "Tested for high-durability school-day active wear",
      icon: "Sparkles",
    },
    {
      title: "Affordable Prices",
      description: "Direct-from-manufacturer transparent pricing",
      icon: "BadgePercent",
    },
    {
      title: "Easy Returns & Exchanges",
      description: "7-day hassle-free size exchange guarantee",
      icon: "RefreshCw",
    },
    {
      title: "Secure Payments",
      description: "100% encrypted checkout with UPI, Cards & Net Banking",
      icon: "Lock",
    },
  ],
  categories: [
    {
      id: "summer-dress",
      name: "Summer Dress",
      slug: "summer-dress",
      icon: "Shirt",
      accent: "yellow",
    },
    {
      id: "winter-dress",
      name: "Winter Dress",
      slug: "winter-dress",
      icon: "Layers",
      accent: "blue",
    },
    {
      id: "thermals",
      name: "Thermals",
      slug: "thermals",
      icon: "Flame",
      accent: "pink",
    },
    {
      id: "school-shoes",
      name: "School Shoes",
      slug: "school-shoes",
      icon: "Footprints",
      accent: "navy",
    },
    {
      id: "school-bags",
      name: "School Bags",
      slug: "school-bags",
      icon: "Backpack",
      accent: "blue",
    },
    {
      id: "socks-stockings",
      name: "Socks & Stockings",
      slug: "socks-stockings",
      icon: "Sparkle",
      accent: "yellow",
    },
    {
      id: "belts-accessories",
      name: "Belts & Accessories",
      slug: "belts-accessories",
      icon: "Tag",
      accent: "green",
    },
    {
      id: "stationery",
      name: "Stationery",
      slug: "stationery",
      icon: "BookOpen",
      accent: "blue",
    },
    {
      id: "water-bottles",
      name: "Water Bottles",
      slug: "water-bottles",
      icon: "Droplet",
      accent: "blue",
    },
    {
      id: "lunch-boxes",
      name: "Lunch Boxes",
      slug: "lunch-boxes",
      icon: "Package",
      accent: "yellow",
    },
  ],
  brands: [
    { name: "TirupatiBalajee", slug: "tirupati-balajee" },
    { name: "Van Heusen Kids", slug: "van-heusen-kids" },
    { name: "Allen Solly Junior", slug: "allen-solly-junior" },
    { name: "Bata", slug: "bata" },
    { name: "Nivia", slug: "nivia" },
    { name: "Cello", slug: "cello" },
    { name: "Camlin", slug: "camlin" },
  ],
};
